spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demospringmvc
    username: postgres
    password: Test1234=
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cache:
    type: caffeine
  mail:
    host: smtp.gmail.com
    username: adoptionpetwards@gmail.com
    port: 587
    password: Test1234=
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

#  spring.mail.host=smtp.gmail.com
#  spring.mail.port=587
#  spring.mail.username=adoptionpetwards@gmail.com
#  spring.mail.password=Test1234=
#  spring.mail.properties.mail.smtp.auth=true
#  spring.mail.properties.mail.smtp.starttls.enable=true

#Note : Si tu utilises un autre service SMTP,
#  tu devras adapter l'URL du serveur et d'autres paramètres
#  (par exemple, pour SendGrid ou Mailgun).