spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/laboapipetward
    username: postgres
    password: postgres123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cache:
    type: caffeine
  mail:
    host: smtp.gmail.com
    username: adoptionpetwards@gmail.com
    port: 587
    password: Test1234=
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080